[manifest]
version = "1.0.0"
dump_lua = true
priority = -9

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
position = 'after'
pattern = '''function Card:update(dt)'''
payload = '''
    BV.Jokers.update(self)

'''

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
position = 'after'
pattern = '''if getmetatable(self) == Card then 
        table.insert(G.I.CARD, self)
    end
'''
payload = '''

BV.Jokers.init(self)
'''